### ISSUE TITLE
Error retrieving links from 9anime/aniwave

### ISSUE THREAD

**Issue by BogWater** [KillerDogeEmpire/avocado-extensions#7]
Cloudstream has been returning 'no links found' for the past couple of days. I noticed that mycloud went down on aniwave around the time this issue started occurring.

Here's a screenshot of the provider test logs:
![Screenshot_20231023_181338_CloudStream](https://github.com/KillerDogeEmpire/avocado-extensions/assets/72219564/f2f6c177-24fa-4412-afd7-68894dc10cb9)

**Comment by KillerDogeEmpire** [comment]
@BogWater will be fixed soon, gotta wait for the api to update with 9anime's changes since they changed the site. nothing I can do to fix, will fix itself when api is updated
